spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/auth_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        order_updates: true
        generate_statistics: true
    open-in-view: false
  mail:
    host: ${APP_MAIL_HOST:smtp.gmail.com}
    port: ${APP_MAIL_PORT:587}
    username: ${APP_MAIL_USERNAME}
    password: ${APP_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${APP_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${APP_MAIL_STARTTLS_ENABLE:true}
    from:
      address: ${APP_MAIL_FROM_ADDRESS}
      name: ${APP_MAIL_FROM_NAME}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

jwt:
  secret: ${APP_JWT_SECRET:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: ${APP_JWT_EXPIRATION:3600000}
  refresh-expiration: ${APP_JWT_REFRESH_EXPIRATION:86400000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.guilherme.authapi: DEBUG
    org.springframework.security: INFO 